### ISSUE TITLE
Release New Version for Scala 3.0.0-M3

### ISSUE THREAD

**Issue by darkfrog26** [circe/circe-generic-extras#118]
Please release a new version of this for Scala 3.0.0-M3 as I rely on it for several projects that are stuck waiting.

**Comment by travisbrown** [comment]
Just a heads up that this will probably be a non-trivial project, and I don't have any plans to work on it myself (unless someone wants to pay for that), since I don't personally use this module.

If there are particular features you need, it might be possible to add them directly to the new derivation mechanisms in circe-core.

**Comment by darkfrog26** [comment]
@travisbrown the only major item that I need is support for default params in case classes. I think I can live without this if I had that.

**Comment by darkfrog26** [comment]
@travisbrown any updates on this? This is the only thing holding back several of my projects getting releases on Dotty.

**Comment by travisbrown** [comment]
I'm not going to be able to add anything specific like that to the Dotty-specific code in circe-core myself, just noting that it might be possible if someone wants to contribute it, and likely easier than migrating the macros here.

**Comment by darkfrog26** [comment]
It doesn't need to be in the Dotty-specific code does it? I would think just a configuration option to enable it in core would be quite useful in general and remove any need for this library I think.

**Comment by darkfrog26** [comment]
@travisbrown I know you're busy, but if you could point me in the right direction to add this support, I'd be happy to give it a try.

**Comment by travisbrown** [comment]
@darkfrog26 The problem is that the language and standard library don't provide any way to abstract over members with default arguments. You have two choices: write your own macro, which is what [circe-derivation](https://github.com/circe/circe-derivation) does, or use Shapeless's `Default` type class, which is what `generic.extras` does. Shapeless's approach is also macro-based, and in general I'd always prefer to use someone else's macros over maintaining my own, but `Default` in particular has always felt pretty awkward to me, and it has non-trivial overhead at both compile-time and runtime.

This is why there's nothing like this in the core Circe repo: because both of the options I know of are fairly terrible in practice. I may have missed something, and there may be some nicer way to do this in Scala 3 that I'm not aware of. If I were in your position I'd probably try to write something like a `ACursor => ACursor` helper method that would fill in missing fields with defaults, and then you could use that like this:

```scala
implicit val decodeMyCaseClass: Decoder[MyCaseClass] =
  deriveDecoder[MyCaseClass].prepare(addDefaults[MyCaseClass])
```

Or whatever. That way you don't have to worry about doing all the generic derivation business yourself—you can just use circe-generic, which should be mostly source-compatible across Scala 2 / 3. I have no idea what the current status of Shapeless for Scala 3 is, but I guess it's possible that it exists and already has the `Default` type class, which would probably make this approach not excessively painful to implement.

**Comment by darkfrog26** [comment]
@travisbrown thanks for the detailed response. I appreciate it. I'll give this some additional thought and let you know if I'm able to come up with a good solution that might be a viable PR for Circe.

**Comment by froth** [comment]
@travisbrown sorry for hijacking this conversation :) the only feature I use from generic-extras is .withDiscriminator. I find it very useful to create json representations compatible with openapi `oneOf / discriminator` (https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/). Is there any chance of this feature going mainline into generic-simple?

**Comment by travisbrown** [comment]
@froth I think that supporting that representation would be a good candidate for a Scala 3 implementation in circe-core, and this is something I'd been thinking of implementing myself. I can't promise that there will be a friendly way to do that across Scala 2 and 3, but it'll almost certainly be in circe-core 0.15.0 for Scala 3.

**Comment by froth** [comment]
@travisbrown great news! Thanks for the fast reply.
